# Generated by Django 5.0.6 on 2024-05-24 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_alter_user_borrowed_books'),
        ('adm', '0002_remove_book_availability_book_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='borrowed_books',
            field=models.ManyToManyField(blank=True, related_name='borrowers', to='adm.book'),
        ),
    ]
