# Generated by Django 5.0.6 on 2024-05-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Availability',
        ),
        migrations.AddField(
            model_name='book',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Novels', 'Novels'), ('Short Stories', 'Short Stories'), ('Romance', 'Romance'), ('Fantasy', 'Fantasy'), ('Educational', 'Educational'), ('Kids', 'Kids')], max_length=250),
        ),
    ]
